server:
  port: 8003

spring:
  application:
    name: eureka-colony-client1

eureka:
  #instance:
    #注册中心ip地址，对应列表中的Applicaiton
    #appname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka,http://localhost:9100/eureka
    register-with-eureka: true
    fetch-registry: true

