server:
  port: 9100

spring:
  application:
    #集群的服务名称需要相同
    name: app-order

eureka:
  instance:
    #注册中心ip地址
    appname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
    register-with-eureka: true
    fetch-registry: true
